name: flutter_application_1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization:
  intl: any 


# google maps

  # dio:
  # google_maps_flutter:
  # flutter_polyline_points:

# firebase
  # firebase_core:


#   # databse
#   # cloud_firestore:

#   # user auth
#   firebase_auth:
#   google_sign_in:

#   # analytics
#   firebase_analytics:

#   # crashalytics
#   firebase_crashlytics:

# fonts
  google_fonts: ^4.0.4


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.0
  google_nav_bar: 
  flutter_localizations:
    sdk: flutter
  geolocator: ^11.0.0
  google_gemini: ^0.1.2
  camera: ^0.10.5+5
  firebase_core: ^2.20.0
  path: ^1.8.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets: 
    - assets/images/


