// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfzLFnql9cXXlvDUu7op7X3h2nA18TjFw',
    appId: '1:841015537227:web:c25747e35e7bb5c3f6a7ce',
    messagingSenderId: '841015537227',
    projectId: 'doctor-ji-63a56',
    authDomain: 'doctor-ji-63a56.firebaseapp.com',
    storageBucket: 'doctor-ji-63a56.appspot.com',
    measurementId: 'G-42RJZDHPLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO7jrlBqfpHiPCw4lEcGpAgGVoR1jFzCI',
    appId: '1:841015537227:android:8b34038115462f57f6a7ce',
    messagingSenderId: '841015537227',
    projectId: 'doctor-ji-63a56',
    storageBucket: 'doctor-ji-63a56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYyJ6EmTVwV0xRnEQTUDXyWeauel8dx1M',
    appId: '1:841015537227:ios:8cf89df87ae404aff6a7ce',
    messagingSenderId: '841015537227',
    projectId: 'doctor-ji-63a56',
    storageBucket: 'doctor-ji-63a56.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYyJ6EmTVwV0xRnEQTUDXyWeauel8dx1M',
    appId: '1:841015537227:ios:8cf89df87ae404aff6a7ce',
    messagingSenderId: '841015537227',
    projectId: 'doctor-ji-63a56',
    storageBucket: 'doctor-ji-63a56.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
